Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.define "prometheus-test-box" do |prom|
        prom.vm.box = "ubuntu/bionic64"
        prom.vm.hostname = "prometheus-test-box"
        prom.vm.provision "ansible" do |ansible|
            ansible.playbook = "configure-box.yaml"
        end
    end
end